"""
This type stub file was generated by pyright.
"""

from typing import Awaitable, Callable, Optional, Union
from flet_core.page import Page
from flet_core.types import WebRenderer

def app(session_handler: Union[Callable[[Page], Awaitable], Callable[[Page], None]], proxy_path: Optional[str] = ..., assets_dir: Optional[str] = ..., app_name: Optional[str] = ..., app_short_name: Optional[str] = ..., app_description: Optional[str] = ..., web_renderer: WebRenderer = ..., use_color_emoji: bool = ..., route_url_strategy: str = ..., upload_dir: Optional[str] = ..., upload_endpoint_path: Optional[str] = ..., max_upload_size: Optional[int] = ..., secret_key: Optional[str] = ..., session_timeout_seconds: int = ..., oauth_state_timeout_seconds: int = ...): # -> FastAPI:
    """
    Mount all Flet FastAPI handlers in one call.

    Parameters:
    * `session_handler` (function or coroutine) - application entry point - a method called for newly connected user. Handler must have 1 parameter: `page` - `Page` instance.
    * `assets_dir` (str, optional) - an absolute path to app's assets directory.
    * `app_name` (str, optional) - PWA application name.
    * `app_short_name` (str, optional) - PWA application short name.
    * `app_description` (str, optional) - PWA application description.
    * `web_renderer` (WebRenderer) - web renderer defaulting to `WebRenderer.CANVAS_KIT`.
    * `use_color_emoji` (bool) - whether to load a font with color emoji. Default is `False`.
    * `route_url_strategy` (str) - routing URL strategy: `path` (default) or `hash`.
    * `upload_dir` (str) - an absolute path to a directory with uploaded files.
    * `upload_endpoint_path` (str, optional) - absolute URL of upload endpoint, e.g. `/upload`.
    * `max_upload_size` (str, int) - maximum size of a single upload, bytes. Unlimited if `None`.
    * `secret_key` (str, optional) - secret key to sign and verify upload requests.
    * `session_timeout_seconds` (int, optional)- session lifetime, in seconds, after user disconnected.
    * `oauth_state_timeout_seconds` (int, optional) - OAuth state lifetime, in seconds, which is a maximum allowed time between starting OAuth flow and redirecting to OAuth callback URL.
    """
    ...

