"""
This type stub file was generated by pyright.
"""

from fastapi import Request

class FletOAuth:
    """
    HTTP handler for OAuth callback.
    """
    def __init__(self) -> None:
        ...
    
    async def handle(self, request: Request): # -> RedirectResponse | HTMLResponse:
        """
        Handle OAuth callback request.

        Request must contain minimum `code` and `state` query parameters.

        Returns either redirect to a Flet page or a HTML page with further instructions.
        """
        ...
    


