"""
This type stub file was generated by pyright.
"""

import fastapi
from typing import Any, Awaitable, Callable, Coroutine, Dict, List, Optional, Sequence, Type, Union
from fastapi.params import Depends
from starlette.middleware import Middleware
from starlette.requests import Request
from starlette.responses import Response
from starlette.routing import BaseRoute

class FastAPI(fastapi.FastAPI):
    def __init__(self, *, debug: bool = ..., routes: Optional[List[BaseRoute]] = ..., title: str = ..., summary: Optional[str] = ..., description: str = ..., version: str = ..., openapi_url: Optional[str] = ..., openapi_tags: Optional[List[Dict[str, Any]]] = ..., servers: Optional[List[Dict[str, Union[str, Any]]]] = ..., dependencies: Optional[Sequence[Depends]] = ..., default_response_class: Type[Response] = ..., redirect_slashes: bool = ..., docs_url: Optional[str] = ..., redoc_url: Optional[str] = ..., swagger_ui_oauth2_redirect_url: Optional[str] = ..., swagger_ui_init_oauth: Optional[Dict[str, Any]] = ..., middleware: Optional[Sequence[Middleware]] = ..., exception_handlers: Optional[Dict[Union[int, Type[Exception]], Callable[[Request, Any], Coroutine[Any, Any, Response]],]] = ..., on_startup: Optional[Sequence[Callable[[], Optional[Awaitable]]]] = ..., on_shutdown: Optional[Sequence[Callable[[], Optional[Awaitable]]]] = ..., terms_of_service: Optional[str] = ..., contact: Optional[Dict[str, Union[str, Any]]] = ..., license_info: Optional[Dict[str, Union[str, Any]]] = ..., openapi_prefix: str = ..., root_path: str = ..., root_path_in_servers: bool = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., callbacks: Optional[List[BaseRoute]] = ..., webhooks: Optional[fastapi.routing.APIRouter] = ..., deprecated: Optional[bool] = ..., include_in_schema: bool = ..., swagger_ui_parameters: Optional[Dict[str, Any]] = ..., generate_unique_id_function: Callable[[fastapi.routing.APIRoute], str] = ..., **extra: Any) -> None:
        ...
    


