"""
This type stub file was generated by pyright.
"""

import os
from typing import Optional, Tuple
from fastapi.staticfiles import StaticFiles
from flet_core.types import WebRenderer
from starlette.types import Receive, Scope, Send

logger = ...
class FletStaticFiles(StaticFiles):
    """
    Serve Flet app static files.

    Parameters:

    * `app_mount_path` (str) - absolute URL of Flet app. Default is `/`.
    * `assets_dir` (str, optional) - an absolute path to app's assets directory.
    * `app_name` (str, optional) - PWA application name.
    * `app_short_name` (str, optional) - PWA application short name.
    * `app_description` (str, optional) - PWA application description.
    * `web_renderer` (WebRenderer) - web renderer defaulting to `WebRenderer.CANVAS_KIT`.
    * `use_color_emoji` (bool) - whether to load a font with color emoji. Default is `False`.
    * `route_url_strategy` (str) - routing URL strategy: `path` (default) or `hash`.
    * `websocket_endpoint_path` (str, optional) - absolute URL of Flet app WebSocket handler. Default is `{app_mount_path}/ws`.
    """
    def __init__(self, proxy_path: Optional[str] = ..., assets_dir: Optional[str] = ..., app_name: Optional[str] = ..., app_short_name: Optional[str] = ..., app_description: Optional[str] = ..., web_renderer: WebRenderer = ..., use_color_emoji: bool = ..., route_url_strategy: str = ..., websocket_endpoint_path: Optional[str] = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    def lookup_path(self, path: str) -> Tuple[str, Optional[os.stat_result]]:
        """Returns the index file when no match is found.

        Args:
            path (str): Resource path.

        Returns:
            [tuple[str, os.stat_result]]: Always retuens a full path and stat result.
        """
        ...
    


