"""
This type stub file was generated by pyright.
"""

from flet_runtime.utils import is_mobile

"""Provide the current Flet version."""
version = ...
def update_version(): # -> str:
    """Return the current version or default."""
    ...

if not version and not is_mobile():
    version = ...
